HrModule.PresentationMvc/Controllers/ContractController.cs
using HrModule.Application.Shared;
using HrModule.Domain.Entities;
using HrModule.Domain.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HrModule.PresentationMvc.Controllers
{
    public class ContractController : Controller
    {
        private readonly IGetContractsQuery _getContractsQuery;
        private readonly IEditContractCommand _editContractCommand;

        public ContractController(IGetContractsQuery getContractsQuery, IEditContractCommand editContractCommand)
        {
            _getContractsQuery = getContractsQuery;
            _editContractCommand = editContractCommand;
        }

        /// <summary>
        /// Main list. Contains filters and reference to partial view ListData.
        /// </summary>
        /// <returns></returns>
        public ViewResult List()
        {
            return View();
        }

        /// <summary>
        /// Table with all contracts. Processing filtering and paging.
        /// </summary>
        /// <param name="currentFilter">Current filter values</param>
        /// <param name="page">Page number. Default is 1</param>
        /// <returns></returns>
        public PartialViewResult ListData(ContractFilter currentFilter, int page = 1)
        {
            ViewBag.CurrentFilter = currentFilter;

            GetContractsResponse model = new GetContractsResponse { Contracts = new List<Contract>(), PagingInfo = new PagingInfo() };

            try
            {
                model = _getContractsQuery.Execute(currentFilter, page);
            }
            catch(Exception ex)
            {
                // log this exception 
            }

            return PartialView(model);
        }

        /// <summary>
        /// Edit dialog. Used to edit existing contract or create a new one.
        /// </summary>
        /// <param name="contractId">Contract id. Id = 0 means that new contract will be created</param>
        /// <returns></returns>
        public ViewResult Edit(int contractId)
        {
            Contract contract = _getContractsQuery.ExecuteAll().Contracts
                .FirstOrDefault(c => c.ContractID == contractId);

            return View(contract);
        }

        /// <summary>
        /// Saving data about contract. Used in edit and create.
        /// </summary>
        /// <param name="contract">Contract data</param>
        /// <returns>Redirect to List or stay on current view</returns>
        [HttpPost]
        public ActionResult Edit(Contract contract)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _editContractCommand.Execute(contract);
                    TempData["message"] = string.Format("Saved {0} ", contract.Name);
                }
                catch(Exception ex)
                {
                    // log this exception 
                    TempData["message"] = string.Format("Could not save {0}. {1}", contract.Name, ex.Message);
                }

                return RedirectToAction("List");
            }
            else
            {
                return View(contract);
            }
        }

        /// <summary>
        /// Create a new contract. View edit is used.
        /// </summary>
        /// <returns></returns>
        public ViewResult Create()
        {
            return View("Edit", new Contract());
        }
    }
}

HrModule.PresentationMvc/Controllers/SalaryController.cs
using HrModule.Application.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HrModule.PresentationMvc.Controllers
{
    public class SalaryController : Controller
    {
        private readonly ICalculateSalaryQuery _salaryQuery;

        public SalaryController(ICalculateSalaryQuery salaryQuery)
        {
            _salaryQuery = salaryQuery;
        }

        /// <summary>
        /// This is used when new contract is created. Asynchronous call calculates salary for selected data.
        /// </summary>
        /// <param name="workingas">Programmer or Tester</param>
        /// <param name="experience">In years</param>
        /// <returns>Salary value</returns>
        [HttpPost]
        public ActionResult CalculateSalary(string workingas, int experience)
        {
            decimal calculatedSalary = 0;

            try
            {
                calculatedSalary = _salaryQuery.Execute(workingas, experience);
            }
            catch(Exception ex)
            {
                // log this exception 
            }

            return Json(new { success = true, salary = calculatedSalary });
        }
    }
}

HrModule.PresentationMvc/Views/Contract/Edit.cshtml
<script type="text/javascript">
    //This script is used to calculate salary in asynchronous way. Event on click is attached to button. 
    //Value is put in salary field.
    $(document).ready(function() {
        $('#calculateSalary').click(function () {

            var workingas = $('#WorkingAs').val();
            var experience = $('#Experience').val();

            $.ajax('@Url.Action("CalculateSalary", "Salary")', {
                type: 'POST',
                dataType: 'json',
                data : {
                    'workingas': workingas,
                    'experience' : experience
                },
                    success: function(data, status, jqXHR) {
                        if ("success" === status) {
                            $('#Salary').val(data.salary);
                        } else {
                            alert('This Product ID is not valid. Try again!');
                        }
                    }
        });
    });
    });
</script>


@using HrModule.Domain.Entities

@model HrModule.Domain.Entities.Contract

@{
    ViewBag.Title = "Edit";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Name</h3>
    </div>

    @using (Html.BeginForm("Edit", "Contract"))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ContractID)

            <div class="form-group">
                <label>Name:</label>
                @Html.TextBox("Name", null, new { @class = "form-control" })
                @Html.ValidationMessage("Name")
            </div>

            <div class="form-group">
                <label>Working as:</label>
                @Html.DropDownList("WorkingAs", new SelectList(Enum.GetNames(typeof(PositionType))), new { @class = "form-control" })

            </div>

            <div class="form-group">
                <label>Experience:</label>
                @Html.TextBox("Experience", null, new { @class = "form-control" })
                @Html.ValidationMessage("Experience")
            </div>

            <div class="form-group">
                
                <label>Salary:</label>
                @Html.TextBox("Salary", null, new { @class = "form-control", @readOnly = "readonly" })
                @Html.ValidationMessage("Salary")
                <input id="calculateSalary" type="button" value="Calculate salary for selected data" class="btn btn-default" />
            </div>
        </div>

        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and back to list", "List", null, new { @class = "btn btn-default" })
        </div>
    }


</div>

HrModule.PresentationMvc/Views/Contract/List.cshtml
@using HrModule.Domain.Entities

@model HrModule.Application.Shared.GetContractsResponse

@{
    ViewBag.Title = "Contracts";
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        UpdateTargetId = "tableBody",
        Url = Url.Action("ListData")
    };
}

<div @*class="panel panel-default"*@>
    
    <div @*class="panel-heading"*@ class="page-header">
        <h3>List of contracts</h3>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            Actions
        </div>

        <div class="panel-body">
            @Html.ActionLink("Add new contract", "Create", null, new { @class = "btn btn-default" })
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            Filtering contracts
        </div>
        
        @using (Ajax.BeginForm("ListData", null, ajaxOpts, new { @class = "panel-body form-horizontal" }))
        {
                <div class="form-group">
                    <label class="col-xs-2">Name:</label>
                    <div class="col-xs-10">
                        @Html.TextBox("Name", null, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-2">Working as:</label>
                    <div class="col-xs-10">
                        @Html.DropDownList("WorkingAs", new SelectList(new[] { "" }.Concat(Enum.GetNames(typeof(PositionType)))), new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-2">Experience:</label>
                    <div class="col-xs-10">
                        @Html.TextBox("Experience", null, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-2">Salary:</label>
                    <div class="col-xs-10">
                        @Html.TextBox("Salary", null, new { @class = "form-control" })
                    </div>
                </div>

            <div @*class="panel-footer"*@ >
                <input type="submit" value="Apply filter" @*class="btn btn-primary"*@ class = "btn btn-default"/>
            </div>
        }
            
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            Predefined filters
        </div>

        <div class="panel-body">
            @Ajax.ActionLink("Experience 5 years", "ListData", new { ExperienceOperator="=", Experience = 5 }, new AjaxOptions { UpdateTargetId = "tableBody" }, new { @class = "btn btn-default" })
            @Ajax.ActionLink("Salary more then 5k", "ListData", new { SalaryOperator=">", Salary = 5000 }, new AjaxOptions { UpdateTargetId = "tableBody" }, new { @class = "btn btn-default" })
            @Ajax.ActionLink("Clear filter", "ListData", new { }, new AjaxOptions { UpdateTargetId = "tableBody" }, new { @class = "btn btn-default" })
        </div>
    </div>

    <div class="panel panel-default">
        @Html.Action("ListData", new { })
    </div>

</div>

HrModule.PresentationMvc/Views/Contract/ListData.cshtml
@model HrModule.Application.Shared.GetContractsResponse

<div id="tableBody" class="panel-body">

    <div class="ajaxLink btn-group pull-right">

        @for (int index = 1; index <= Model.PagingInfo.TotalPages; index++)
        {
            if (index == Model.PagingInfo.CurrentPage)
            {
                @Ajax.ActionLink("Page " + index, "ListData", new { page = index, Name = ViewBag.CurrentFilter.Name, WorkingAs = ViewBag.CurrentFilter.WorkingAs, ExperienceOperator = ViewBag.CurrentFilter.ExperienceOperator, Experience = ViewBag.CurrentFilter.Experience, SalaryOperator = ViewBag.CurrentFilter.SalaryOperator, Salary = ViewBag.CurrentFilter.Salary }, new AjaxOptions { UpdateTargetId = "tableBody" }, new { @class = "selected btn-primary btn btn-default" })
            }
            else
            {
                @Ajax.ActionLink("Page " + index, "ListData", new { page = index, Name = ViewBag.CurrentFilter.Name, WorkingAs = ViewBag.CurrentFilter.WorkingAs, ExperienceOperator = ViewBag.CurrentFilter.ExperienceOperator, Experience = ViewBag.CurrentFilter.Experience, SalaryOperator = ViewBag.CurrentFilter.SalaryOperator, Salary = ViewBag.CurrentFilter.Salary }, new AjaxOptions { UpdateTargetId = "tableBody" }, new { @class = "btn btn-default" })
            }
        }
    </div>

    <table class="table table-striped table-condensed table-bordered">

        <tr>
            <th>Name</th>
            <th>Working as</th>
            <th>Experience</th>
            <th>Salary</th>
        </tr>

        @foreach (var item in Model.Contracts)
        {
            <tr>
                <td>@Html.ActionLink(item.Name, "Edit", new { item.ContractID })</td>
                <td>@item.WorkingAs</td>
                <td>@item.Experience</td>
                <td>@*@item.Salary*@ @string.Format("{0:n0}", item.Salary)</td>
            </tr>
        }

    </table>


</div>

HrModule.PresentationMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
</head>
<body>
    
    <div class="container body-content">

        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>    
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</body>
</html>